[project]
name = "vmemu"

[subdir.dependencies]

[target.vmemu]
type = "executable"

sources = [
    "src/**.cpp",
    "include/**.hpp",
]
include-directories = [
    "include",
]
link-libraries = [
    "vmprofiler",
    "unicorn",
    "cli-parser",
]
compile-definitions = [
    "NOMINMAX"
]